### PR TITLE
Meta: use new WHATWG boilerplate and license

### PR DESCRIPTION
**Pull request by domenic**
Do not merge until https://github.com/tabatkins/bikeshed/pull/1155 is merged.

***
<a href="https://whatpr.org/encoding/132.html" title="Last updated on Jan 8, 2018, 10:40 AM GMT (4695f12)">Preview</a> | <a href="https://whatpr.org/encoding/132/2ef4c13...4695f12.html" title="Last updated on Jan 8, 2018, 10:40 AM GMT (4695f12)">Diff</a>

### CODE REVIEW

**Comment by annevk** [comment]
See https://github.com/whatwg/sg/issues/48.

**Comment by domenic** [comment]
I mean, should we block all further development on encoding until that gets resolved, or what?

**Comment by annevk** [comment]
I added a commit that makes the additional changes that will likely satisfy the requirements. Review appreciated. The final commit message probably needs to be revised and should mention https://github.com/whatwg/meta/issues/65 as I've tackled that here as well.

**Comment by annevk** [comment]
@domenic could you have a final look?

**Comment by domenic** [comment]
LGTM!

**Pull request merged**
