### PR TITLE
Document an implementation buffer trick

### PR DESCRIPTION
**Pull request by annevk**
***
[Preview](https://encoding.spec.whatwg.org/branch-snapshots/annevk/implementation-considerations/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/encoding/ee2bd34...279eac3.html)

### CODE REVIEW

**Comment by annevk** [comment]
@hsivonen worth doing?

**Comment by annevk** [comment]
Preview: https://encoding.spec.whatwg.org/branch-snapshots/annevk/implementation-considerations/#implementation-considerations

**Comment by hsivonen** [comment]
I think this is worth doing, but I suggest highlighting that the single-byte buffer will always hold an ASCII value for gb18030 decoder and will always hold either 0x24 or 0x28 for the ISO-2022-JP decoder.

**Comment by annevk** [comment]
@hsivonen I was going to add that encoders do not need an additional buffer at all, but what about the ISO-2022-JP encoder?

**Comment by annevk** [comment]
(I added what the single-byte buffer would contain by the way.)

**Comment by hsivonen** [comment]
> I was going to add that encoders do not need an additional buffer at all, but what about the ISO-2022-JP encoder?

The encoders are all stateless, except for the ISO-20222-JP encoder, and the only piece of state it needs is ASCII/Roman/JIS0208. No buffer needed.

(Additionally, the only reason the encoders need to process EOF is to transition ISO-2022-JP back into the ASCII state. Even the ISO-2022-JP encoder even without EOF signaling would produce a stream that decodes without errors.)

> (I added what the single-byte buffer would contain by the way.)

Thank you.

**Comment by annevk** [comment]
I added a short paragraph on encoders.

**Comment by hsivonen** [comment]
LGTM. Thank you.

**Pull request merged**
