### PR TITLE
Fixes #95: added two rowspan=2 to the 8859-9-i table

### LINKED ISSUE #95: iso-8859-8-i encoding entry in table not valid html (missing columns)
https://encoding.spec.whatwg.org/#legacy-single-byte-encodings

In preparing to cut a new copy of encoding for the W3C reference version, I ran validator. The table of singlebyte encodings includes ISO 8859-8-I by itself in the left column of the table, since it shares data with ISO 8859-8. However, the result isn't "valid" HTML. The two new columns need rowspan="2" added. Pull request forthcoming.

### PR DESCRIPTION
**Pull request by aphillips**
***
[Preview](https://s3.amazonaws.com/pr-preview/aphillips/encoding-1/master.html) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/encoding/f2c6682...aphillips:92c23a9.html)

### CODE REVIEW

**Comment by annevk** [comment]
Could you please remove the quotes for consistency? (I tried to fix it up, but I can't push to your branch. Probably because you created a fork from master.)

**Comment by annevk** [comment]
Also, I guess I was right to worry about all the warnings for the other resources making actual errors get lost in the noise. Not really sure what to do about it.

**Comment by aphillips** [comment]
Fixed in above commit. Sorry I missed the consistency the first time.

**Comment by annevk** [comment]
Thanks!

**Pull request merged**
