### PR TITLE
Add Streams Explainer

### PR DESCRIPTION
**Pull request by ricea**
Add a new file, streams-explainer.md, which explains the integration of
Streams into the Encoding Standard for a general audience.

### CODE REVIEW

**Comment by annevk** [comment]
This seems great, but perhaps better suited as a blog post? @domenic what do you think about putting this on blog.whatwg.org?

**Comment by domenic** [comment]
I think there are two audiences here. One is folks who appreciate explainers, like spec reviewers and blink-dev. The other is web developers. The content won't be too different in each case, but I'd imagine for the first audience we want to couch this more as a proposal, whereas for the latter audience we want to publish an announcement of a new feature. And the latter audience might want to be linked to some of the gory details, instead of consuming it all inside their feed reader.

So I think we should keep the explainer as-is, either in this repo or in @ricea's fork, for folks who appreciate explainers. And after we've successfully landed the spec change, we can work on turning it into a blog post.

WDYT?

**Comment by annevk** [comment]
Okay, I guess I don't quite see explainers being part of Living Standards or their repositories. If a feature is sufficiently unclear it should just get an introduction section or some such.

**Comment by ricea** [comment]
@annevk Thanks, I will withdraw this pull request.

Hopefully the feature won't need much explanation in the standard itself. I expect a couple of examples will be enough.

**Pull request closed without merging**
