### PR TITLE
Editorial: ensure various bits link properly

### PR DESCRIPTION
**Pull request by annevk**
***
[Preview](https://encoding.spec.whatwg.org/branch-snapshots/annevk/editorial/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/encoding/9ce8d47...fcf3484.html)

### CODE REVIEW

**Comment by annevk** [comment]
@tabatkins I have a dfn "index" with ID "index" and this clashes with the newly added "Index" section which also wants ID "index" and is auto-generated by Bikeshed. I tried using Translate IDs, but that just ends up replacing both, which is later followed by deduping, rather than using Translate IDs only for the IDs generated by Bikeshed. Is that a bug or am I doing something wrong here?

**Comment by domenic** [comment]
My two cents: although it does sound like this scenario wasn't considered while designing Bikeshed, and thus is a little wacky, I think it's better to not define something with the ID "index", so that in every Bikeshed spec `#index` goes to the same thing (the index of terms). `concept-index` or similar might be the way to go.

**Comment by annevk** [comment]
@tabatkins ping.

@domenic I guess I could rename it too, but that seems bad if someone uses that fragment today.

**Comment by tabatkins** [comment]
Hmm, I can definitely see the confusion with how `Translate IDs` is defined ("maps Bikeshed-generated IDs to manually-specified IDs") and how it actually works (attempts to translate all and only definitions, headings, issues, and examples).

I should fix this to do what it actually says on the tin.

**Comment by tabatkins** [comment]
And I just pushed. Using it on "index" should work now, and only rename the Index ID, not your dfn with a manually-specified ID.

**Comment by annevk** [comment]
Thanks!

**Pull request merged**
