### PR TITLE
Avoid teaching bad UTF-8 math.

### PR DESCRIPTION
**Pull request by hsivonen**
1. Instead of subtracting a magic number, do a bitwise AND to pick a number of least-significant bits that makes sense if you consider the UTF-8 bytes bitwise.
2. Instead of shifting by variable amounts in order to put all bits into their final destination directly, always shift by a constant six and let the higher bits be shifted a number of times.

### CODE REVIEW

**Comment by annevk** [comment]
Thank you. Would you be okay with you or me turning the "i.e." bits into paragraph notes? The existing encoding algorithms don't have any inline explanations.

**Comment by hsivonen** [comment]
Works for me. I don't have the time to do it myself today, though, so please go ahead if you have the time.

**Comment by annevk** [comment]
If you could review my fixup that'd be great. No rush though. (Note that it includes the generated file.) After that I'll squash, merge, and land on master.

**Comment by hsivonen** [comment]
r+. Looks good. Thanks.

**Pull request merged**
